### ISSUE TITLE
How to draw Chromaticities(cie xy) diagram

### ISSUE THREAD

**Issue by Henxun** [tompazourek/Colourful#119]

**Comment by tompazourek** [comment]
This is probably a duplicate of #80

**Comment by tompazourek** [comment]
> hi，tommpourek How to calculate the boundaries of the horseshoe

I have never done that, so I don't know exactly. Sorry. I think this is related https://en.wikipedia.org/wiki/Planckian_locus.

This library is more about conversion between color spaces, it doesn't have all tools for colorimetry, unfortunately :(

**Comment by Henxun** [comment]
> > hi，tommpourek How to calculate the boundaries of the horseshoe
> 
> I have never done that, so I don't know exactly. Sorry. I think this is related https://en.wikipedia.org/wiki/Planckian_locus.
> 
> This library is more about conversion between color spaces, it doesn't have all tools for colorimetry, unfortunately :(

thank you!i got no idea for this, it's so difficult for me
