### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [tompazourek/Colourful#138]
Maybe You will be interested in hosting API Explorer online:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/colourful/api/Colourful.RGBColor.html)

https://www.robiniadocs.com/d/colourful/api/Colourful.RGBColor.html

**Comment by tompazourek** [comment]
Looks really nice, thank you. I'll add this badge to README.
