### ISSUE TITLE
Example of processing video frames from video file

### ISSUE THREAD

**Issue by zmarty** [tompazourek/Colourful#36]
Hi there,

Thanks a lot for working on this project. I am trying to process video frames from a Rec2020 ST2084 video file and plot a brightness waveform (Y axis is nits) like I am used to seeing in DaVinci Resolve.

Do you have any end to end example of using your library to access individual frames from a video file?

Thanks!

**Comment by hacky97** [comment]
I don't think that a video decoding sample would be in place here. When that'done just feed the RGB data to the Colourful library.
