### ISSUE TITLE
Replicating Photoshop's LAB Mode

### ISSUE THREAD

**Issue by RoyiAvital** [tompazourek/Colourful#37]
Hello,

If you take RGB values (Let's say sRGB) and convert to LAB with D50, do you get exact values like in Photoshop?

Thank You.

**Comment by tompazourek** [comment]
Hi Royi, I think you should get the same values as in Photoshop. However, I don't currently have any Photoshop license, so I cannot confirm this.

**Comment by RoyiAvital** [comment]
I see.
Because I'm having trouble getting Photoshop's LAB values - http://stackoverflow.com/questions/42558443.

I thought you have experience with it.

**Comment by tompazourek** [comment]
Do you have some sets of sRGB triplets and corresponding Photoshop's LAB triplets that are the expected results of the conversion?

If you do, I can try running them through Colourful and we'll see if it will get the same results or not.

**Comment by RoyiAvital** [comment]
Hi,

You can grab the whole image from the link above and compare it to the Grayscale image (L Channel).

The images are on [0, 255] range so the L Channel image should be scaled to [0, 100].

Thank You.
