### ISSUE TITLE
ColourFulConverter Question

### ISSUE THREAD

**Issue by KSEIinnovations** [tompazourek/Colourful#45]
Hello, 

I am trying to get the converter working with VB.net but I can't for the life of me figure out what is to go in the new constructor of the ColourfulConverter? Anyone that could help. When I run it like this I get the following error: System.ArgumentOutOfRangeException: 'The maximum value is 1'

Dim input As RGBColor = New RGBColor(Px.R, Px.G, Px.B)
Dim LAB As LabColor
Dim conver = New ColourfulConverter()
LAB = conver.ToLab(input)

**Comment by tompazourek** [comment]
The R, G, and B parameters should be ranging from 0 to 1. It might be that you have those in the range from 0 to 255. If that's the case, simply divide them by 255.

Hope it helps.
