### ISSUE TITLE
Unity3D requires .NET version <=4.6

### ISSUE THREAD

**Issue by hacky97** [tompazourek/Colourful#46]
Any chance that the code could be down-ported back to .NET 4.6? Unity requires at most .NET 4.6 and this code utilizes .NET 7 functions like "type pattern matching".
The 'in' and 'readonly' keyword can be left out,  "get=>" can easily be rewritten and a throw after a double questionmark is easily fixed, but "type pattern matching" needs some rework. 

Maybe add unity support in a separate branch? Would you accept a pull request?I could add some extra's to calculate averages from textures etc...

**Comment by tompazourek** [comment]
Hi there,

The "type pattern matching" is a feature of the C# language, not the .NET Framework. Even though the library uses features from a later version of C# (7.3), it can still be used in .NET 4.5 or .NET Standard 1.1, which means you should be able to use it with Unity.

The `in` and `readonly` were added recently with the v2 release to eliminate allocations as a performance improvement. See: https://github.com/tompazourek/Colourful/pull/43

If you want to use a version without these, just use the previous version, [v1](https://github.com/tompazourek/Colourful/tree/1.2.2).

**Comment by hacky97** [comment]
Thanks for the clarification Tom. I keep mixing c# versions with .NET versions. 
Unity won't swallow it however. I set he API compatibility level of Unity 2017.3.0f3 to .NET 4.6 and it simply spits errors about the above syntax. 
I guess that's because Unity does not *really* use .NET, but a forked version that's being kept "up-to-date" on top of Mono. 
![image](https://user-images.githubusercontent.com/6864766/46396721-7e681080-c6f0-11e8-8f8b-cfa69f95adee.png)
![image](https://user-images.githubusercontent.com/6864766/46396863-e3bc0180-c6f0-11e8-8a99-11e16b92739d.png)

**Comment by tompazourek** [comment]
@hacky97 It looks like your Unity project doesn't support the higher version of C# than 6.0 (unless it can be configured somewhere).

But why do you need to include the source code of the library? Can't you just reference the binaries or the NuGet package?

**Comment by hacky97** [comment]
No, I don't think I really need the source. 
The nuget package manager won't fool Unity however, but with the nuget asset from the Unity asset store I was able to download Colourful into the unity project and run a test. 
Thanks!
