### ISSUE TITLE
JzAzBz color space

### ISSUE THREAD

**Issue by SLS8** [tompazourek/Colourful#51]
It would be useful to add the Jzazbz color space . Thank you

**Comment by SLS8** [comment]
from the java version found on a [forum](https://stackoverflow.com/questions/49464451/jzazbz-java-implementation-precision), with the suggested corrections   

      static readonly private double b = 1.15;
      static readonly private double g = 0.66;
      static readonly double c1 = 3424 / Math.Pow(2, 12);
      static readonly double c2 = 2413 / Math.Pow(2, 7);
      static readonly double c3 = 2392 / Math.Pow(2, 7);
      static readonly double n = 2610 / Math.Pow(2, 14);
      static readonly double p = 1.7 * (2523 / Math.Pow(2, 5));
      static readonly double d = -0.56;
      static readonly double d0 = 1.6295499532821567 * Math.Pow(10, -11);
      

      static double[] XYZToJab(double[] xyz)
      {
         double[] jab = new double[3];

         double[] XYZp = new double[3];
         XYZp[0] = b * xyz[0] - ((b - 1) * xyz[2]);
         XYZp[1] = g * xyz[1] - ((g - 1) * xyz[0]);
         XYZp[2] = xyz[2];

         double[] LMS = new double[3];
         LMS[0] = 0.41478972 * XYZp[0] + 0.579999 * XYZp[1] + 0.0146480 * XYZp[2];
         LMS[1] = -0.2015100 * XYZp[0] + 1.120649 * XYZp[1] + 0.0531008 * XYZp[2];
         LMS[2] = -0.0166008 * XYZp[0] + 0.264800 * XYZp[1] + 0.6684799 * XYZp[2];

         double[] LMSp = new double[3];
         for (int i = 0; i < 3; i++)
         {
            LMSp[i] = Math.Pow((c1 + (c2 * Math.Pow(LMS[i] / 10000, n))) / (1 + (c3 * Math.Pow(LMS[i] / 10000, n))), p);
         }

         double[] Iab = new double[3];
         Iab[0] = 0.5 * LMSp[0] + 0.5 * LMSp[1];
         Iab[1] = 3.524000 * LMSp[0] - 4.066708 * LMSp[1] + 0.542708 * LMSp[2];
         Iab[2] = 0.199076 * LMSp[0] + 1.096799 * LMSp[1] - 1.295875 * LMSp[2];

         jab[0] = ((1 + d) * Iab[0] / (1 + d * Iab[0])) - d0;
         jab[1] = Iab[1];
         jab[2] = Iab[2];

         return jab;
      }

      static double[] JabToXYZ(double[] jab)
      {
         double[] xyz = new double[3];

         double[] Iab = new double[3];
         Iab[0] = (jab[0] + d0) / (1 + d - d * (jab[0] + d0));
         Iab[1] = jab[1];
         Iab[2] = jab[2];

         double[] LMSp = new double[3];
         LMSp[0] = 1.0 * Iab[0] + 0.138605043271539 * Iab[1] + 0.058047316156119 * Iab[2];
         LMSp[1] = 1.0 * Iab[0] - 0.138605043271539 * Iab[1] - 0.058047316156119 * Iab[2];
         LMSp[2] = 1.0 * Iab[0] - 0.096019242026319 * Iab[1] - 0.811891896056039 * Iab[2];

         double[] LMS = new double[3];
         for (int i = 0; i < 3; i++)
         {
            LMS[i] = 10000 * Math.Pow((c1 - Math.Pow(LMSp[i], 1 / p)) / ((c3 * Math.Pow(LMSp[i], 1 / p)) - c2), 1 / n);
         }

         double[] XYZp = new double[3];
         XYZp[0] = 1.924226435787607 * LMS[0] - 1.004792312595365 * LMS[1] + 0.037651404030618 * LMS[2];
         XYZp[1] = 0.350316762094999 * LMS[0] + 0.726481193931655 * LMS[1] - 0.065384422948085 * LMS[2];
         XYZp[2] = -0.090982810982848 * LMS[0] - 0.312728290523074 * LMS[1] + 1.522766561305260 * LMS[2];

         xyz[0] = (XYZp[0] + (b - 1) * XYZp[2]) / b;
         xyz[1] = (XYZp[1] + (g - 1) * xyz[0]) / g;
         xyz[2] = XYZp[2];

         return xyz;
      }

**Comment by tompazourek** [comment]
I found this, which could be useful: https://observablehq.com/@jrus/jzazbz

It also includes code for the delta Ez color difference.

**Comment by SLS8** [comment]
Thanks. I think that formula is only needed for JzCzhz, the polar coordinates version of JzAzBz.
For JzAzBz it's the classic euclidean distance since it's a perceptually uniform space, as described by the authors.
More C code here: http://im.snibgo.com/jzazbz.htm

**Comment by tompazourek** [comment]
@SLS8 I started some work on this in [feature/jzazbz](https://github.com/tompazourek/Colourful/tree/feature/jzazbz). It looks interesting.

It still needs more tests, and maybe some related clean-up. I'll continue when I find some time again.

**Comment by SLS8** [comment]
Great. Thank you!

**Comment by tompazourek** [comment]
I'll leave this issue open until the work on the Jzazbz color space is finished and it's released. Just so it's visible that there's still some WIP.

@SLS8 Thanks for the original idea!

**Comment by tompazourek** [comment]
Now implemented in the `vnext` branch and part of 3.0.0-alpha1 (still needs more tests though).
