### ISSUE TITLE
RGB Result in 0-255

### ISSUE THREAD

**Issue by derLarsonaut** [tompazourek/Colourful#57]
Sorry for this newbie question but;
Is it possible to get the RGB Result in 0-255?
Thanks Lars

**Comment by tompazourek** [comment]
Hi @derLarsonaut, each RGB channel will be between 0 and 1. But if you multiply a channel by 255, you'll get a result between 0 and 255.

**Comment by KelSolaar** [comment]
Note that if the intent is to go from float to integer representation, the data will also need to be encoded with a transfer function of some sort, e.g. Gamma 2.2 or sRGB Inverse EOTF.

**Comment by tompazourek** [comment]
@KelSolaar I am not sure if this is correct. You can work with sRGB colors both in range 0..1 and 0..255. And then you can work with linear RGB colors both in 0..1 and 0..255.

It's true that for some color processing computations, it might be better to transfer to linear RGB, do the computations there, and then transfer back to sRGB for display purposes. But I don't believe it's really related to whether the range is 0..1 or 0..255 or whether the number is a float, or an integer. Am I wrong?

**Comment by KelSolaar** [comment]
It is correct :)

The most obvious reason for transforming from [0, 1] to [0, 255] is that one is about to convert to integer representation. If it is the intent (and I purposely stated it in my previous comment), then one must encode his floating-point data before scaling and casting to int or serious quantization defects will be introduced.

> It's true that for some color processing computations, it might be better to transfer to linear RGB (via some companding function), do the computations there, and then transfer back to sRGB for display purposes (via some inverse companding function).

Depending your job it is actually "True for almost all".

Cheers,

Thomas

**Comment by tompazourek** [comment]
@KelSolaar If you have a color in linear RGB space and then convert to sRGB, the companding function will be applied (at least that's how it currently is in Colourful). What you're saying is that if you want to represent the sRGB in 0..255, you should apply the companding function again? That would mean it would be applied twice.

**Comment by tompazourek** [comment]
@KelSolaar Actually now that I think about it, maybe the confusion is that in Colourful you can use sRGB both in `RGBColor` and `LinearRGBColor`.

So it depends on what @derLarsonaut uses. If you're using `LinearRGBColor`, you should probably convert to `RGBColor` (during which Colourful will apply companding function), and then multiply it by 255. If you're already using `RGBColor` in Colourful, it should be fine to just multiply by 255.

**Comment by KelSolaar** [comment]
> What you're saying is that if you want to represent the sRGB in 0..255, you should apply the companding function again?

I'm not saying that nor implying that however quoting you:

> But if you multiply a channel by 255, you'll get a result between 0 and 255.

In that case, the transfer function is not applied, and if @derLarsonaut converts the data to integer representation, he will have quantization defects!

**Comment by KelSolaar** [comment]
Ah! You keep editing while I'm writing :)

**Comment by tompazourek** [comment]
@KelSolaar Sorry about that!

**Comment by KelSolaar** [comment]
All good! :)

**Comment by derLarsonaut** [comment]
Thank you for your answer. 
I am just looking for an easy way to convert it to 0-255. 
The output is "RGB [R=0.65, G=0.32, B=0.21]" for example. With my low coding experience i would split the output to an array. I was woundernig if there is an easier way.  
The main reason for all this is some sort of error investigation. For a very long time (several years) we use Color Draw 8 to convert Lab to RGB. A while ago we figured out, that the values converted by corel differs greatly from any other converter. For example Lab 44,80 34,07 31,92 is in Corel RGB 214 - 15 - 0. In your code its 0,65 - 0,32 0,21 (167,75 81,6 53,55) like in EasyRGB.
I appreciate every tip. 
Regards Lars

**Comment by tompazourek** [comment]
@derLarsonaut If you're using the `RGBColor` class, it should be correct.

There's also one more way if you're using the full .NET Framework, and that is to use the `System.Drawing.Color` class that's present in the full .NET Framework. That one stores each RGB channel in a `byte` type from 0 to 255.

This should work:

```csharp
var rgbColor = new Colourful.RGBColor(0.65, 0.32, 0.21); // or get it as a result of LAB conversion
System.Drawing.Color drawingColor = rgbColor.ToColor();
Console.WriteLine(drawingColor.R); // 166
Console.WriteLine(drawingColor.G); // 82
Console.WriteLine(drawingColor.B); // 54
```

**Comment by derLarsonaut** [comment]
Perfect, thank you!
