### ISSUE TITLE
Chromaticity

### ISSUE THREAD

**Issue by WindyPT25** [tompazourek/Colourful#80]
I want to show color graphs on the program. But I didn't find a way in the library.
 Can this library do that?

![250px-PlanckianLocus](https://user-images.githubusercontent.com/67569180/85968404-3f630e00-b9ef-11ea-9607-440d045ba795.png)

**Comment by tompazourek** [comment]
Hi, @WindyPT25

Yes, you can try this example: [ColourfulHorseshoe.zip](https://github.com/tompazourek/Colourful/files/4845017/ColourfulHorseshoe.zip)

If you have any more questions or feedback, feel free to re-open this.
