### ISSUE TITLE
Thread safety of ColourfulConverter

### ISSUE THREAD

**Issue by hillin** [tompazourek/Colourful#84]
Should (or is it intended that) `ColourfulConverter` be implemented as thread-safe? Because conceptually all functions it provides seem quite pure, and it would be really convenient if this class is thread-safe so we can share its instance among parallel actions (which is quite common in image processing). But to my observation, it is currently not. If for some reason it cannot be implemented thread-safely, I guess it's better to have that fact documented.

**Comment by tompazourek** [comment]
I think there are a few issues why the `ColourfulConverter` is not thread-safe... And I agree that it would be better if it were, I definitely how that is useful in image processing...

The conversion engine is getting a major rewrite in the next version (v3), see the branch `vnext` for more info (the README contains updated examples with the new API):  https://github.com/tompazourek/Colourful/tree/vnext

I think it should be better with regards to thread-safety in that next version (and also performance and extensibility). Also, it will be possible to create a separate converter for each thread (but I'm not sure if that's necessary). You can already try it in the [**3.0.0-beta1** version](https://www.nuget.org/packages/Colourful/3.0.0-beta1).

If you'd be willing to try it, I'd be happy to get some feedback.

**Comment by hillin** [comment]
Thanks. The next version seems pretty promising, although I'm fully occupied recently so I'm afraid I cannot try the beta version yet, sorry for that.

**Comment by tompazourek** [comment]
@hillin Sure, I understand, I'm quite busy myself, so I only find little time for the open-source projects. :)

I hope to release a stable v3 soon. It just needs some more documentation, maybe some more test cases, and it should be ready.
