### ISSUE TITLE
.NET Standard 2.0 drawing support

### ISSUE THREAD

**Issue by tonyqus** [tompazourek/Colourful#92]
I notice that System.Drawing.Color is not supported in .NET Standard 2.0 version.

System.Drawing has been supported in .NET Core for some while. Do you have plan to release a new version that supports explict convertion from System.Drawing.Color to RGBColor?

**Comment by tompazourek** [comment]
Yes, this sounds like a good idea. I was not aware of this, and thanks for pointing this out.

I'm not devoting too much time into this project lately, I have the [v3 beta version](https://github.com/tompazourek/Colourful/tree/vnext) ready, but it still needs more documentation which I'm procrastinating to write.

I hope to look into this soon, and maybe get it out as part of the v3 version.

**Comment by tompazourek** [comment]
I added this in the [vnext](https://github.com/tompazourek/Colourful/tree/vnext) branch.

I also released this to NuGet as part of [3.0.0-beta3](https://www.nuget.org/packages/Colourful/3.0.0-beta3). I'm still working on the documentation that I want to finalize before the stable v3 release... But it should be ready to use.

Closing this.
