### ISSUE TITLE
Possible bug on Lab to RGB conversion

### ISSUE THREAD

**Issue by pagliu81** [tompazourek/Colourful#96]
Hello,
I'm using the conversion from Lab colour space to Rgb and I ran in a possible error.
I'm using illuminants D50, but I noticed it's the same with others.

The values taken are
L = 39.19931413
a = -45.65942708
b = 11.40527685

and the results are
R = -0.42
G = 0.43
B = 0.28

this is the code used:
>var lab = new LabColor(39.19931413, -45.65942708,11.40527685);
>var rgb = new ConverterBuilder().FromLab(Illuminants.D50).ToRGB().Build().Convert(LabColour);

As far as I know and also from your documentation the values of R G B should be between 0 and 1,
so why the result for the R is a negative -0.42?

Thank you for your time.

**Comment by tompazourek** [comment]
See also: https://github.com/tompazourek/Colourful/blob/master/docs/spaces-rgb.md#clamp-and-normalize-intensity

**Comment by pagliu81** [comment]
Thank you for the quick response and sorry if I thought it was a bug.

**Comment by tompazourek** [comment]
@pagliu81 No problem 😉 Even though it wasn't a bug, after all, I'm still glad you took the time and contributed with your well written report. It can still help others with the same issue.

And also I'm always just happy someone's actually using my code 😄
